version: '3.5'
services:
  pgadmin:
    image: dpage/pgadmin4:9.3.0
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@superintendencia.com
      PGADMIN_DEFAULT_PASSWORD: superintendencia
    ports:
      - 5050:80
    networks:
      network_service:
        ipv4_address: 10.10.2.30
      network_db:
        ipv4_address: 10.10.1.10
    dns:
      - 10.10.2.3

networks:
  network_service:
    external: true
  network_db:
    external: true